### ISSUE TITLE
Overhaul documentation

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#219]
I am pretty unhappy with the current documentation and think that we can do much better.

- [ ] Add brief summary on the landing page that explains relation to other assets (https://github.com/laminlabs/bionty/issues/200)
- [ ] Extending bionty (ontologies, new ontologies, new entities) (https://github.com/laminlabs/bionty/issues/178 & https://github.com/laminlabs/bionty/issues/154). We discussed adding crispra genes as a use-case.
- [ ] Looking up unmatched terms (https://github.com/laminlabs/bionty/issues/179)
- [x] Merge readout into lookup
- [ ] Mention [lnschema-bionty](https://github.com/laminlabs/lnschema-bionty/) wherever fit.

**Comment by sunnyosun** [comment]
Also this one: https://github.com/laminlabs/bionty/issues/179
